### PR TITLE
Make boost and jansson gitmodules

### PR DESCRIPTION
**Pull request by marblenix**
boost: v1.79.0
jansson: v2.10

Jansson repo was found by using this link: https://github.com/drachtio/drachtio-server/tree/db4c7600c290cd636fce057d523f0d6ac528e28d/deps/jansson-2.10#documentation

Boost repo was found similarly by using this link: https://www.boost.org/users/faq.html from the link about the GitHub bug tracking system.

### CODE REVIEW

**Comment by davehorton** [comment]
can you remove `deps/libzrtp` from .gitmodule to sync with latest main?

```
[submodule "deps/libzrtp"]
        path = deps/libzrtp
        url = https://github.com/traviscross/libzrtp.git
````

**Comment by davehorton** [comment]
hmm.  Now it looks like you've removed boost from .gitmodules, which I thought was your whole point (to have that as a submodule)
```
$ cat .gitmodules
[submodule "deps/prometheus-cpp"]
	path = deps/prometheus-cpp
	url = https://github.com/jupp0r/prometheus-cpp.git
[submodule "deps/sofia-sip"]
	path = deps/sofia-sip
	url = https://github.com/davehorton/sofia-sip.git
	branch = main
[submodule "deps/cpp-bredis"]
	path = deps/cpp-bredis
	url = https://github.com/basiliscos/cpp-bredis.git
```

**Comment by marblenix** [comment]
Thank you for catching that. I suppose that's what I get when I trust GitHub to do the rebase for me.

**Comment by davehorton** [comment]
I'm not seeing a change in .gitmodules when I pull the latest?

**Comment by marblenix** [comment]
That's odd… https://github.com/marblenix/drachtio-server/blob/all-deps-as-submodules/.gitmodules
it should be there.

Can you try deleting your local branch and fetching it again?

**Comment by davehorton** [comment]
oh, you are right.  My bad!

**Pull request merged**
