### PR TITLE
CI: Update SonarCloud to 6.2 + Java 17

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
Well,

> Could not find a default branch for project with key 'drachtio_drachtio-server'. Make sure project exists.

Why is it even enabled then?

**Comment by davehorton** [comment]
actually, another contributor added it and I accepted it, probably without enough review first

**Comment by orgads** [comment]
@ghenry Can you please explain?

**Comment by ghenry** [comment]
Did I do this?

**Comment by orgads** [comment]
> Did I do this?

Yes, here:
- #204

**Comment by ghenry** [comment]
It's static analysis for your code.

**Comment by orgads** [comment]
> It's static analysis for your code.

I understand, but the project must be setup in sonarcloud for this to work...

**Comment by ghenry** [comment]
Yep, I gave Dave instructions at the time. I guess he didn't have time.

**Comment by orgads** [comment]
Ok, I changed it to `workflow_dispatch` (manual execution only) until registration is done.

@davehorton please approve.

**Review by davehorton — APPROVED** [review]

**Pull request merged**
