### PR TITLE
Use correct size for wire protocol message

### PR DESCRIPTION
**Pull request by sip2thefuture**
Basically,  utf8_strlen is only useful if you want to display the character, but has no meaning when trying to access the data.

### CODE REVIEW

**Comment by davehorton** [comment]
I'd be interested to add a test case, what sort of data being sent would illustrate the problem?  I currently have test cases for utf8 encoded things like emojis and those do work.

**Comment by sip2thefuture** [comment]
I don't have test data right now, they might work, but utf8_strlen is not the correct way to count the byteSize (you do the same on the wire-protocol side).

https://github.com/sip2thefuture/drachtio-srf/blob/bf5c0be486569a01c5a6e03064fcd1424baaaa99/lib/wire-protocol.js#L251

std::size is the equivalent of what you did there, not utf8_streln.

**Comment by sip2thefuture** [comment]
Leave it another bit as it needs to be in pair with drachtio-srf changes

**Comment by davehorton** [comment]
@sip2thefuture  I've pushed the changes to drachtio-srf in version 0.5.0 of same, could you update the [package.json in the test folder](https://github.com/drachtio/drachtio-server/blob/ad1366d32d5005d2be449981ebc21002347780d3/test/package.json#L17) to refer to same?

**Comment by sip2thefuture** [comment]
@davehorton done!

**Comment by davehorton** [comment]
my bad @sip2thefuture, actually the version needed is 5.0.0.  Could you push that one last change?

**Comment by sip2thefuture** [comment]
Should be fine now

**Comment by davehorton** [comment]
I'm releasing this in drachtio-server 0.9.0 and it should be partnered with drachtio-srf 5.0.0 or higher

**Pull request merged**
